# -*- coding: utf-8 -*-
"""Task4_DA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VxAupN1cRs4wVLFfwW_Vd5pZ1uXln9HR
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm

# Lorenz96 model
def lorenz96(x, F = 8.0):
  #dx_i/dt = (x_{i+1} - x_{i-2}) x_{i-1} - x_i + F
  N = len (x)
  dxdt = np.zeros(N)

  for i in range(N):
     x_prev2 = x[(i - 2) % N]  # X_{j-2}
     x_prev1 = x[(i - 1) % N]  # X_{j-1}
     x_next1 = x[(i + 1) % N]  # X_{j+1}
     dxdt[i] = (x_next1 - x_prev2) * x_prev1 - x[i] + F

  return dxdt

#RK4
#y(t+1) = y(t) + (k1 + k2 + k3 + k4) h/6
# k1 = f(t,y)                 k2 = f(t+h/2, y + hk1/2)
# k3 = f(t+h/2, y + hk2/2)    k4 = f(t+h, y+hk3)
def rk4(x, dt, F=8.0):
  k1 = lorenz96(x, F)
  k2 = lorenz96(x + 0.5 * dt * k1, F)
  k3 = lorenz96(x + 0.5 * dt * k2, F)
  k4 = lorenz96(x + dt * k3, F)
  x_next = x + (dt / 6.0) * (k1 + 2*k2 + 2*k3 + k4)

  return x_next

#creating data for 2 years
N = 40
F = 8.0
dt = 0.05 #6hours
steps_per_years = 365 * 4
total_steps = steps_per_years * 2

x = F * np.ones(N)
x[N//4] += 0.01  #small perturbation

all_data = np.zeros((total_steps+1, N))
all_data[0] = x

for t in range(total_steps):
  x = rk4(x, dt, F)
  all_data[t+1] = x

print(all_data.shape)

#throw away the first year data
#start from the sec year data as truth

truth = all_data[steps_per_years:]
print(truth.shape)

#Mersene Twister to make normal distribution
rng = np.random.default_rng(seed=42)
noise = rng.standard_normal(size=truth.shape)
print(noise.shape)

#observation data
obs = truth + noise

#creating histogram
plt.hist(noise.flatten(), bins=100, density=True, color="steelblue", alpha=0.7, label="Histogram of randoms")
x_range = np.linspace(-4, 4, 300)
plt.plot(x_range, norm.pdf(x_range, 0, 1), color="red", lw=2, label="N(0,1) Logical PDF")

plt.xlabel("noise")
plt.ylabel("density")
plt.title("Histogram of observation noise N(0, 1)," f"mean={noise.flatten().mean():.4f},  std={noise.flatten().std():.4f})")
plt.grid(True, alpha=0.3)
plt.legend()
plt.show()

print("noise mean =", np.mean(noise))
print("noise variance =", np.var(noise))

#compare true nature vs observation
time_days = np.arange(truth.shape[0]) / 4.0 #for 6 hr unit

plt.figure(figsize=(12, 4))
plt.plot(time_days, truth[:, 0], color="steelblue", lw=1.2,  label="True nature")
plt.scatter(time_days, obs[:, 0], s=8, color="tomato", alpha=0.6, label="Observation with noise")
plt.xlabel("Time [days]")
plt.ylabel("x_0")
plt.title("True nature and observation data")
plt.legend()
plt.grid(True)

plt.show()

#the latter one year be true nature
# y_obs = true nature + noise → obs(var)

#  1 prediction(xb) → x_t^b = M(x_{t-1}^a)
#  2 prediction error covariance(Pb) → P_t^b = M_t P_{t-1}^a M_t^T,  P_t^b = cI
#  3 Kalman Gain → K_t=P_t^bH^T(HP_t^bH^T+R)^{-1}, H = I (全変数を観測), R = I (観測誤差分散が1)
#  4 analysis → x_t^a=x_t^b+K_t(y_t^o-Hx_t^b)
#  5 analysis error covariance (Pa) → P_t^a=(I-K_tH)P_t^b
#  H=I　xは40個の状態変数全てで、yは状態にノイズを足した観測変数全てになっているから　Hx = x
#  R=I  誤差分散は1、各変数の観測誤差が独立していることを仮定したので、共分散は0
#  P_t^b=cI

#Tangent Linear Matrix (to create matrix point)
#\delta x(t+dt)=M \delta x(t)
def tangent_linear_matrix (x, dt):
  N = len(x)
  M = np.zeros((N,N))

  for j in range(N):
    j_minus2 = (j - 2)% N
    j_minus1 = (j - 1)% N
    j_plus1 = (j + 1) % N

    M[j, j_minus2] = -x[j_minus1] * dt
    M[j, j_minus1] = (x[j_plus1] - x[j_minus2]) * dt
    M[j, j] = 1.0 - dt
    M[j, j_plus1] = x[j_minus1] * dt

  return M

#KF cycle
def EKF_cycle(xa, Pa, y_obs, dt, F, H, R, inflation):
  #1. tangent linear matrix (M)
  M = tangent_linear_matrix(xa, dt)

  #2. prediction forecast state (xb)
  xb = rk4(xa, dt, F)

  #3. prediction covariance (Pb)
  Pb = M @ Pa @ M.T
  Pb = (1 + inflation) * Pb

  #4. Kalman Gain
  S = H @ Pb @ H.T + R
  K = Pb @ H.T @ np.linalg.inv(S)

  #5. analysis
  xa_new = xb + K @ (y_obs - H @ xb)

  #6. analysis covarience
  I = np.eye(len(xa))
  Pa_new = (I - K @ H) @ Pb

  return xa_new, Pa_new, xb, Pb, K

#main starting function
N = 40
H = np.eye(N)
R = np.eye(N)
#obs_indices = np.arange(0, N, 2)
#H = np.eye(N)[obs_indices]
#R = np.eye(len(obs_indices))
#y_obs = obs[t, obs_indices]

xa = obs[0].copy()        #initial analysis
Pa = 10 * np.eye(N)        #initial analysis covariance

inflation_values = [0.0, 0.03, 0.05, 0.055, 0.06, 0.08]
result = {}

#xb_save = []
#xa_save = []
#rmse_b_list = []
#rmse_a_list = []

for inflation in inflation_values:
  xa = obs[0].copy()
  Pa = 10 * np.eye(N)

  xb_save = []
  xa_save = []
  pb_save = []
  pa_save = []
  spread_a_list = []
  rmse_b_list = []
  rmse_a_list = []
  for t in range(1, truth.shape[0]):
    xa, Pa, xb, Pb, K = EKF_cycle(xa, Pa, obs[t], dt, F, H, R, inflation)

    xb_save.append(xb.copy())
    xa_save.append(xa.copy())
    pb_save.append(Pb.copy())
    pa_save.append(Pa.copy())
    spread_a = np.sqrt(np.trace(Pa) / N)
    spread_a_list.append(spread_a)

    #RMSE

    rmse_b_ = np.sqrt(np.mean((xb - truth[t]) ** 2))
    rmse_b_list.append(rmse_b_)

    rmse_a_ = np.sqrt(np.mean((xa - truth[t]) ** 2))
    rmse_a_list.append(rmse_a_)

  result[inflation] = {
        "forecast": np.array(xb_save),
        "analysis": np.array(xa_save),
        "Pb": np.array(pb_save),
        "Pa": np.array(pa_save),
        "analysis_spread": np.array(spread_a_list),
        "mean_analysis_spread": np.mean(spread_a_list),
        "forecast_rmse": np.array(rmse_b_list),
        "analysis_rmse": np.array(rmse_a_list),
        "mean_forecast_rmse": np.mean(rmse_b_list),
        "mean_analysis_rmse": np.mean(rmse_a_list),}

  #result[inflation] = {"forecast_rmse": np.array(rmse_b_list), "analysis_rmse": np.array(rmse_a_list), "mean_forecast_rmse": np.mean(rmse_b_list), "mean_analysis_rmse": np.mean(rmse_a_list),}
#xb_save = np.array(xb_save)
#xa_save = np.array(xa_save)

time_days = np.arange(1, truth.shape[0]) / 4.0
var = 0
start_day = 200
end_day = 300
mask = (time_days >= start_day) & (time_days <= end_day)

fig, axes = plt.subplots(len(inflation_values), 1, figsize=(10, 3 * len(inflation_values)), sharex=True)
fig.suptitle(f"Truth, Observation, Forecast, Analysis  (x_{var}, day {start_day}–{end_day})", fontsize=13)

for ax, inflation in zip(axes, inflation_values):
    xb_save = result[inflation]["forecast"]
    xa_save = result[inflation]["analysis"]

    ax.plot(time_days[mask], truth[1:, var][mask], label="Truth", color="red")
    ax.scatter(time_days[mask], obs[1:, var][mask], label="Observation", s=5, alpha=0.25)
    ax.plot(time_days[mask], xb_save[:, var][mask], label="Forecast / Predict", color="steelblue")
    ax.plot(time_days[mask], xa_save[:, var][mask], label="Analysis", color="black")
    ax.set_ylabel(f"x_{var}")
    ax.set_title(f"inflation={inflation}")
    ax.legend(loc="upper right", fontsize=8)
    ax.grid(True)

axes[-1].set_xlabel("Time [days]")
plt.tight_layout()
plt.show()

for inflation in inflation_values:

    print("inflation =", inflation,
        "Mean Forecast RMSE =", result[inflation]["mean_forecast_rmse"],
        "Mean Analysis RMSE =", result[inflation]["mean_analysis_rmse"],
        "Mean sqrt(tr(Pa)/N) =", result[inflation]["mean_analysis_spread"] )



colors = {
    0.0: "black",
    0.03: "blue",
    0.05: "green",
    0.055: "red",
    0.06: "purple",
    0.08: "brown"
}

plt.figure(figsize=(8, 4))
start_day = 1
end_day = 300
mask = (time_days >= start_day) & (time_days <= end_day)

for inflation in inflation_values:
    rmse = result[inflation]["analysis_rmse"]
    plt.plot(
        time_days[mask],
        rmse[mask],
        label=f"inflation={inflation:.3f}",
        color=colors[inflation],
        linewidth=0.7
    )

plt.xlim(0, 300)
plt.ylim(0, 7)
plt.ylabel("ave RMSE")
plt.title("Analysis RMSE for different inflation values")
plt.legend()
plt.grid(True)
plt.show()

plt.figure(figsize=(8, 4))
mask = (time_days >= 250) & (time_days <= 300)

for inflation in inflation_values:
    rmse = result[inflation]["analysis_rmse"]
    plt.plot(time_days[mask], rmse[mask], label=f"inflation={inflation:.3f}", color = colors[inflation], linewidth = 1)

plt.xlim(250, 300)
plt.ylim(0, 1)
plt.xlabel("time (day)")
plt.ylabel("ave RMSE")
plt.title("Analysis RMSE (zoomed: day 250–300)")
plt.legend()
plt.grid(True)
plt.show()

Pb_005 = result[0.05]["Pb"]
print(Pb_005.shape)

plot_inflations = [0.0, 0.03, 0.055, 0.08]
plot_days = [1, 10, 300]

fig, axes = plt.subplots(
    len(plot_days),
    len(plot_inflations),
    figsize=(14, 17)
)

vmin = -0.3
vmax = 0.3

for i, day in enumerate(plot_days):
    idx = int(day * 4) - 1   # 6時間ごとなので1日=4step

    for j, inflation in enumerate(plot_inflations):
        Pa = result[inflation]["Pa"][idx]

        ax = axes[i, j]
        im = ax.imshow(
            Pa,
            cmap="bwr",
            vmin=vmin,
            vmax=vmax,
            origin="upper"
        )

        ax.set_title(f"Pa  infla={inflation:.2f}  day={day}")
        ax.set_xticks([0, 10, 20, 30, 39])
        ax.set_yticks([0, 10, 20, 30, 39])

cbar_ax = fig.add_axes([0.3, 0.04, 0.4, 0.025])
plt.suptitle("Analysis Error Covariance $P_t^a$", fontsize=18)
fig.subplots_adjust(bottom=0.05, top=0.90, hspace=0.45, wspace=0.25)
fig.colorbar(im, cax = cbar_ax, pad=0.12 ,shrink=0.5, orientation = "horizontal")

plt.tight_layout()
plt.show()

infls = [0.0, 0.03, 0.05, 0.055, 0.06, 0.08,]
means = [1.7451, 0.2827, 0.27135, 0.2711, 0.2715, 0.2754, 0.2815]

plt.figure(figsize=(6,4))
plt.plot(infls, means, marker='o')
plt.xlabel("Inflation δ")
plt.ylabel("Mean Analysis RMSE")
plt.title("Optimization of inflation parameter")
plt.grid(True)
plt.show()

mean_rmse_a = [result[i]["mean_analysis_rmse"] for i in inflation_values]
mean_spread_a = [result[i]["mean_analysis_spread"] for i in inflation_values]

x = np.arange(len(inflation_values))
width = 0.35

plt.figure(figsize=(8, 4))

plt.bar(x - width/2, mean_rmse_a, width, label="Mean Analysis RMSE")
plt.bar(x + width/2, mean_spread_a, width, label="Mean Spread sqrt(tr(Pa)/N)")

plt.xticks(x, [str(i) for i in inflation_values])
plt.xlabel("Inflation δ")
plt.ylabel("Error size")
plt.title("Mean Analysis RMSE vs Mean Spread")

plt.ylim(0, 0.5)
plt.yticks(np.arange(0, 0.51, 0.1))

plt.legend()
plt.grid(axis="y")
plt.show()

#for each inflation to create the whole process nature
#for 50 days
time_days = np.arange(1, truth.shape[0]) / 4.0

var = 0        # x_0
end = 100      # first 50 days
plt.figure(figsize=(14, 4))

plt.plot(time_days[:end], truth[1:end+1, var], label="Truth", linewidth=2)
plt.scatter(time_days[:end], obs[1:end+1, var], label="Observation", s=8, alpha=0.5)
plt.plot(time_days[:end], xb_save[:end, var], label="Forecast / Predict", linewidth=1.2)
plt.plot(time_days[:end], xa_save[:end, var], label="Analysis", linewidth=1.5)

plt.xlabel("Time [days]")
plt.ylabel(f"x_{var}")
plt.title("Truth, Observation, Forecast, and Analysis")
plt.legend()
plt.grid(True)
plt.show()

#whole year
#plt.figure(figsize=(12, 4))
#plt.plot(time_days, truth[1:, var], label="Truth", linewidth=2)
#plt.scatter(time_days, obs[1:, var], label="Observation", s=8, alpha=0.5)
#plt.plot(time_days, xb_save[:, var], label="Forecast / Predict", linewidth=1.2)
#plt.plot(time_days, xa_save[:, var], label="Analysis", linewidth=1.5)

#for whole year
time_days = np.arange(1, truth.shape[0]) / 4.0
start_day = 300
end_day = 355
mask = (time_days >= start_day) & (time_days <= end_day)

plt.figure(figsize=(14, 4))
plt.plot(time_days[mask], truth[1:, var][mask], label="Truth", linewidth=2)
plt.scatter(time_days[mask], obs[1:, var][mask], label="Observation", s=8, alpha=0.4)
plt.plot(time_days[mask], xb_save[:, var][mask], label="Forecast / Predict", linewidth=1.0)
plt.plot(time_days[mask], xa_save[:, var][mask], label="Analysis", linewidth=1.2)

plt.xlabel("Time [days]")
plt.ylabel(f"x_{var}")
plt.title("Truth, Observation, Forecast, and Analysis")
plt.legend()
plt.grid(True)
plt.show()

print("Forecast difference mean:",
      np.mean(np.abs(xb_save[:, var][mask] - truth[1:, var][mask])))

print("Analysis difference mean:",
      np.mean(np.abs(xa_save[:, var][mask] - truth[1:, var][mask])))

print("Observation difference mean:",
      np.mean(np.abs(obs[1:, var][mask] - truth[1:, var][mask])))

#RMSE plot
time_days = np.arange(len(rmse_a_list)) / 4.0

plt.figure(figsize=(12, 4))
plt.plot(time_days, rmse_b_list, label="Forecast RMSE")
plt.plot(time_days, rmse_a_list, label="Analysis RMSE")
plt.xlabel("Time [days]")
plt.ylabel("RMSE")
plt.title("EKF RMSE")
plt.legend()
plt.grid(True)
plt.show()